version: '3.7'

services:
  web:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
      - ./services/web/:/code/
    ports:
      - 5000:5000
    entrypoint: ./deploy/entrypoint.sh
    env_file:
      - ./.env.prod
    depends_on:
      - db

  worker:
    build: .
    restart: always
    image: python:3.9.5-slim-buster
    command: python tasks_manager.py
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - web

  db:
    image: postgres:13-alpine
    restart: always
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=worker_user
      - POSTGRES_PASSWORD=worker_pass
      - POSTGRES_DB=worker1

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: